### ISSUE TITLE
Collect ISBN #’s for entire list.

### ISSUE THREAD

**Issue by unshakenme** [unshakenme/OSPAT#1]
We need to collect and confirm ISBN #’s for every book on the curriculum.

**Comment by CheekeyMonkey** [comment]
Happy to do this if needed. However, I think if you get the linking correct then this should be sufficient.

**Comment by CheekeyMonkey** [comment]
This is now completed in the fork,

**Comment by unshakenme** [comment]
Thank you! Please submit a PR for that when you get a chance.

**Comment by CheekeyMonkey** [comment]
Done. Shall we close this thread?

**Comment by unshakenme** [comment]
Thanks! Closed.

**Comment by CheekeyMonkey** [comment]
Now done.

Looking forward to working with you.

Thx.

**Comment by unshakenme** [comment]
Likewise. Thanks for the help thus far!
