### ISSUE TITLE
Push Access

### ISSUE THREAD

**Issue by CheekeyMonkey** [unshakenme/OSPAT#14]
Could I be granted push access please? Im trying to upload files into the course subject area, i.e. Word docs with images etc however github is saying that I need _"push access"_ to do so.

**Comment by unshakenme** [comment]
Hello @CheekeyMonkey I just added you as a collaborator, please let me know if you are still having issues.

**Comment by unshakenme** [comment]
@CheekeyMonkey I am going to revert this so we can return to the normal pull-request notification/review process. Please let me know if you need push access again in the future and I can adjust as needed.

**Comment by unshakenme** [comment]
Disregard I found another solution we can experiment with that should require review of my pushes as well.
