### ISSUE TITLE
Defining "Framing" - about 7 years ago I made the statement on /r/psychonaut "it's not the picture, it's the frame" let me explain.

### ISSUE THREAD

**Issue by JDonMc** [unshakenme/OSPAT#16]
When you're tripping, it's common for your field of view to expand, you see out of your peripherals further and clearer. The same even applies in closed-eye-visual states. Sometimes you can have an OBE where the peripherals continually forever expand. What this does is it makes the picture that was once there in the middle, a tiny tiny view within the frame of what was there before. Meaning that if you were to think of art piece, say Picasso, then it becomes that it's more-so the surrounding environment that builds the beauty of the picture.

Similarly, "Framing" can also be used to refer to essentially listening to someone speak or reading a sentence about a story, or even hearing it second hand, you take out and take note of certain things within their statements and tend to pull out only what you attached to. Then when you pass the information, that they passed to you, onwards, then you end up re-framing what they said. And sometimes this can be good, sometimes this can be bad, sometimes (usually all the time) there are pros and cons within everything, as well as much much much more. But this is not the end of that process. Framing is infinite and eternal, a continuous chain of forever, passing through and paying it forward, or taking it back.

When someone hears the same story you heard, but they frame it differently than you, you should not be alarmed that they saw something different in it. This is framing in a nutshell, it is ultimately synchronistic (read: co-incident + meaningful - ie Bayesian Impact Theory) and dependent on your attachments. You can only do you.

**Comment by unshakenme** [comment]
Sorry I'm struggling to see how this is relevant to OSPAT. It is missing any suggestions or content for the OSPAT repo. Please refrain from submitting issues without sufficient justification.

**Comment by JDonMc** [comment]
Have you not read your own repo?

https://github.com/unshakenme/OSPAT/blob/main/course-content/navigating-psychedelic-experience/Framing%20-%20BurnZero.pdf

**Comment by unshakenme** [comment]
Admittedly I had not read that yet. Cheekeymonkey is a trust contributor so it was a brief review when he submitted that pull request.

**Comment by JDonMc** [comment]
@unshakenme so tell me why should I contribute to an empty repo?
