### ISSUE TITLE
 Information for People Seeking Training in Psychedelic-Assisted Therapy link goes to 404

### ISSUE THREAD

**Issue by LaplaceCherub** [unshakenme/OSPAT#20]
Information for People Seeking Training in Psychedelic-Assisted Therapy goes to a 404 page on the MAPS website. I tried Googling it and couldn't find a page from MAPS, but I did find [this synopsis](https://psychedelicnetwork.org.uk/information-for-people-seeking-training-in-psychedelic-assisted-therapy/) on the Psychedelic Health Professionals Network website.

**Comment by VoytekBereza** [comment]
I proposed this change in the read.me file to the admins (you can do this yourself aswell!)

**Comment by LaplaceCherub** [comment]
Thanks! I was going to propose a change directly, but since I couldn't find a 1-1 comparable link decided to just raise an issue.

**Comment by unshakenme** [comment]
Very strange they'd remove that article. It 404s from the link on that UK site as well. Maybe we should just remove that and keep the Psychedelic.support article. Thoughts?

**Comment by VoytekBereza** [comment]
Makes sense, its not a huge part of the project.

**Comment by LaplaceCherub** [comment]
Yeah, I agree with switching to the Psychedelic Support summary.

**Comment by unshakenme** [comment]
Alright it has been updated. Thanks for catching this!
